mode: dev

server:
  port: 8080

db:
  master:
    type: postgres
    migrate: true
    host: localhost
    port: 5432
    dbName: postgres
    user: postgres
    password: mysecretpassword
    charSet: utf8
    sslMode: disable
    timezone: Asia/Seoul
  replicas:
    - type: postgres
      host: localhost
      port: 5432
      dbName: postgres
      user: postgres
      password: mysecretpassword
      charSet: utf8
      sslMode: disable
      timezone: Asia/Seoul

logging:
  level: debug
  format: text
